name: Run Python Scripts Daily

on:
  workflow_dispatch:        # 👈 Enables manual trigger
  schedule:
    - cron: '30 2 * * *'     # 👈 Runs daily at 8 AM IST

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Show file structure (for debugging)
        run: ls -la

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script1
        run: python script1.py

      - name: Run script2
        run: python script2.py

      - name: Run script3
        run: python script3.py
